# Generated by Django 5.2.8 on 2025-11-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('committee', "Qo'mita"), ('factory', 'Korxona')], default='factory', max_length=20),
        ),
    ]
