# Generated by Django 5.2.8 on 2025-11-27 06:08

import django.core.validators
import monitoring.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='excess_amount',
            field=models.DecimalField(decimal_places=3, help_text='Ortib ketgan miqdor (kg/soat). Masalan: 1.25', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='penalty_number',
            field=models.CharField(default=monitoring.models.generate_penalty_number, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='trees_required',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
