# Generated by Django 5.2.8 on 2025-11-27 06:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_penalty_excess_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='excess_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.0'), editable=False, help_text='Avtomatik hisoblanadi: current_gas_amount - max_allowed_gas (kg/soat).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.DeleteModel(
            name='PenaltyResponse',
        ),
    ]
